### ISSUE TITLE
Add mapping attribute to allow entities to skip auto unwrapping proxies when calling getter

### ISSUE THREAD

**Issue by longwa** [grails/gorm-hibernate5#102]
Currently, the domain binder wraps getters for ToOne associations to automatically unwrap the proxy when the getter is called:

https://github.com/grails/gorm-hibernate5/blob/03dcb936cfac24da6cac8481f35d942585d77000/grails-datastore-gorm-hibernate5/src/main/groovy/org/grails/orm/hibernate/cfg/HibernateUtils.groovy#L124

This can be a performance issue for cases where we are just getting the association to then associate to another entity or to compare/show the id. In those cases, the proxy never needs to be unwrapped.

With OSIV, it's likely that the proxy unwrapping could be deferred until it's actually used (if ever) and still have a valid session. A few exceptions might be proxy objects that are returned from a nested session, but that could be handled as needed with eager/join fetching.

The proposal is to add a mapping attribute for Hibernate with default as current behavior to prevent any breaking changes:
```
static mapping = {
    autoUnwrapProxies  true 
}
```
This logic will be added to the GrailsDomainBinder.handleLazyProxy method:
```
protected void handleLazyProxy(PersistentEntity domainClass, PersistentProperty grailsProperty) {
        HibernatePersistentEntity persistentEntity = (HibernatePersistentEntity) domainClass;
        Mapping mappedForm = persistentEntity.getMapping().getMappedForm();
        if (mappedForm.isAutoUnwrapProxies()) {
            HibernateUtils.handleLazyProxy(domainClass, grailsProperty);
        }
}
```
I will submit a PR after a short testing period to ensure no unexpected issues if this seems reasonable.

**Comment by longwa** [comment]
I believe the proxy unwrapping logic has been removed in GORM 7.0.0, correct?

If so, I say we close this ticket as it's no longer relevant going forward.

**Comment by graemerocher** [comment]
Yes it has been removed
