### ISSUE TITLE
Getter method for a proxied association can't be overridden

### ISSUE THREAD

**Issue by longwa** [grails/gorm-hibernate5#103]
GORM 6.1.10
Grails 3.3.8

Overriding the `getter` method for a to-one association doesn't work as the getter is ignored by the proxy handling logic when using the field entity reflector.

It doesn't seem like this behavior should depend on the `AccessType.PROPERTY` or `FIELD` since it's being called on the object directly and not involved in the persisting or loading of the entity itself.

This is supported by the fact that for non-associations, you can override the `getter` method regardless of the `AccessType` being used.

The solution that I've tested (and works) is to change this line from:
https://github.com/grails/gorm-hibernate5/blob/03dcb936cfac24da6cac8481f35d942585d77000/grails-datastore-gorm-hibernate5/src/main/groovy/org/grails/orm/hibernate/cfg/HibernateUtils.groovy#L122

To:
```
def propertyValue = PropertyAccessorFactory.forBeanPropertyAccess(thisObject).getPropertyValue(propertyName)
```

**Comment by graemerocher** [comment]
Maybe if a test can provided that reproduces the issue we can take a look at this. Introducing the code you suggest will cause memory problems

**Comment by longwa** [comment]
I'll try to create a test to reproduce. It's not a huge issue, just something we can across at one point. The PropertyAccessorFactory is used in the setter a few lines later so I'm not sure why it might cause memory issues, but I'll take your word for it.

I have some other GORM/Hibernate changes I need to merge so I'll try to knock it all out at once.

**Comment by longwa** [comment]
I believe the proxy unwrapping logic has been removed in GORM 7.0.0, correct?

If so, I say we close this ticket as it's no longer relevant going forward.

**Comment by graemerocher** [comment]
Yes it had been removed

**Comment by dano-giftbit** [comment]
Hi
I'm working on upgrading a grails app with alot of custom getters that aren't being hit anymore. Stepping into the code I'm seeing the same code as described above. Hoping to avoid alot of refactoring and wondering if we can downgrade to a prev version of Gorm to fix? 
(Upgrading to Gorm 7 seems like a big step as we'd likely have to go to Grails 4)

Current versions
 Grails 3.3.10 | Hibernate 5 | Gorm 6.1.12.RELEASE
