### ISSUE TITLE
6.1.11 release artifact version is inconsistent with what grails expects

### ISSUE THREAD

**Issue by dpcasady** [grails/gorm-hibernate5#113]
Other hibernate5 published artifacts have not included the `.RELEASE` suffix. Grails apps/plugins expect to find `6.1.11`, not `6.1.11.RELEASE`:

```
compile "org.grails.plugins:hibernate5:${gormVersion-".RELEASE"}"
```

[It looks like 6.1.10 was published as both `6.1.10` and `6.1.10.RELEASE`](https://repo.grails.org/grails/core/org/grails/plugins/hibernate5/). Can you do the same for 6.1.11?

**Comment by ilopmar** [comment]
It was an error on our side. The right artifact name is without.. `.RELEASE.`. I'll fix it and release the right artifact tomorrow morning.

**Comment by dpcasady** [comment]
Thanks!

**Comment by ilopmar** [comment]
The new artifact has been published. James has also fixed to make sure it doesn't happen again: https://github.com/grails/gorm-hibernate5/commit/25cd49f93733978b8e0874d3a6cc9901085c6a08
