### ISSUE TITLE
Different transcation behavior since 6.1.7

### ISSUE THREAD

**Issue by sburnicki** [grails/gorm-hibernate5#116]
I recently updated gorm-hibernate5 from 6.1.6 to 6.1.10 and a couple of integration tests broke.
I tracked the issue down to a different behavior of gorm-hibernate5 between 6.1.6 and 6.1.7.

The following example test reproduces the issue:
```groovy
        given:
        new Book(name: "TestBook").save(flush: true)

        when:
        def names = testService.getBooksNewTransaction()

        then:
        names == ["TestBook"]
```

given the following service method

```groovy
    @Transactional(propagation = Propagation.REQUIRES_NEW)
    def getBooksNewTransaction() {
        return Book.list().collect{ it.name }
    }
```

The code works fine with gorm-hibernate5 <= 6.1.6 and breaks with gorm-hibernate5 >= 6.1.7
An example repo reproducing this issue can be found here: https://github.com/sburnicki/gorm-test

I'm not quite sure if this behavior will also change my production code where I use MySQL instead of H2.

**Comment by graemerocher** [comment]
Breaks in what way? What is the exception / error?

**Comment by graemerocher** [comment]
it may be related to the method being named like a property getter. can you try rename the method to `listBooksNewTransaction` and see if it makes a difference. There were some changes to prevent the transform applying to getters and setters, maybe that is related.

**Comment by sburnicki** [comment]
I just renamed the methods and got the same behavior. (I also updated the example repo).
It seems to be flushing related since the following test works:
```groovy
        given:
        Book.withNewSession {
           new Book(name: "TestBook").save(flush: true)
        }

        when:
        def names = testService.listBooksNewTransaction()

        then:
        names == ["TestBook"]
```
But unfortunately I'm not very experienced with the real consequences of `withNewSession` oder `save(flush:true)` and why another transaction can or cannot see the changes.

**Comment by graemerocher** [comment]
the flush mode was changed in 6.1.x to manual it may be there was another case where this is not honoured and has been fixed. Flushing is the right thing to do.

Note that that in GORM 7.x Hibernate no loner allows sessions without a transaction, so the `withNewSession` will also need to include `withTransaction`
