### ISSUE TITLE
multiTenancy discriminator mode with many-to-many still results in SQL Exception trying to access tenantId on join table

### ISSUE THREAD

**Issue by jeff-wheatley** [grails/gorm-hibernate5#121]
#58 appears to be identical to the behavior I am seeing in Grails 3.3.5 and 3.3.9.  As this issue was addressed in Gorm 6.1.10, and Grails 3.3.9 includes Gorm 6.1.11, I am assuming this issue should be resolved.  I have my own example app posted on GitHub if useful.

**Comment by puneetbehl** [comment]
@jeff-wheatley It is working your example application as well. Please update to GORM 6.1.10 or later
