### ISSUE TITLE
Where query produces QueryException: duplicate alias

### ISSUE THREAD

**Issue by kktec** [grails/gorm-hibernate5#122]
A Where query that combines the use of 2 expressions using nested properties with an OR produces a "duplicate alias":
`        
String strainFilter = params.filters?.strain
       
 Plant.where {
            if (strainFilter) { 
             seed.strain.code == strainFilter || mother.seed.strain.code == strainFilter  }
 }
`
Either expression used alone works.

A Micronaut groovy app demonstrates the problem:
https://github.com/kktec/wh1

**Comment by puneetbehl** [comment]
It seems to be duplicate of grails/grails-data-mapping#1267

**Comment by snimavat** [comment]
Would like to have this fix before i can upgrade to gorm 7.0.3
@puneetbehl is there a work around for this error, like setting alias manually etc
