### ISSUE TITLE
Special handling for InList dynamic finders with empty list

### ISSUE THREAD

**Issue by nholley** [grails/gorm-hibernate5#128]
Foo.findAllByBarInList([]) throws a SQL exception when that ultimately gets translated to `where foo.bar in ()` which (some|most|all?) databases consider a SQL error. Logically, the BarInList([]) clause is always false, and hence the dynamic finder should just return an empty list. Similarly BarNotInList([]) is always true and should not yield a where clause. It is possible to write defensive code for this, e.g. `def list = []; if (!list) return []`, but that distracts from the primary purpose of the code block to cover a leaky abstraction.

**Comment by graemerocher** [comment]
Related PR https://github.com/grails/grails-data-mapping/pull/1220

**Comment by demon101** [comment]
Related PR https://github.com/grails/grails-data-mapping/pull/1228

**Comment by demon101** [comment]
duplicate of https://github.com/grails/grails-data-mapping/issues/1212

**Comment by nholley** [comment]
You're right, I apologize for the duplicate. Not sure how I failed to see 1212 previously.

**Comment by demon101** [comment]
@nholley  issue was created in another repository and has more than 5 duplicates. 
The bug is very annoying, not only me =)
I hope, my PR will be merged before 6.1.12 gorm release
