### ISSUE TITLE
GORM dirty checking doesn't seem to work with Boolean type

### ISSUE THREAD

**Issue by rvanderwerf** [grails/gorm-hibernate5#130]
Even when using a setter, GORM dirty checking doesn't seem to work with Boolean or boolean in a domain object. Even calling  the setter over setting a property name doesn't make the object dirty so it doesn't save. I came across this fixing integration tests for the spring security core plugin for Grails 4 & GORM 7. I have a PR with a test case that fails to show the issue. Setting the config in the app back to use Hibernate dirty checking config 'hibernateDirtyChecking' works fine as a workaround.

**Comment by jameskleeh** [comment]
Fixed by https://github.com/grails/grails-data-mapping/commit/d5df2f62e3077f76795bd786ea51ea9ea37fe800#diff-d30c8d50edc4b1f1441c4fcf7f9bd01b
