### ISSUE TITLE
GrailsDomainBinder$CollectionType.INSTANCES being static results in devtools restart issues

### ISSUE THREAD

**Issue by zyro23** [grails/gorm-hibernate5#139]
follow-up of grails/grails-core#11357.

`GrailsDomainBinder$CollectionType.INSTANCES` being `static` can cause exceptions on devtools restart for certain use-cases (e.g. using a enum collection in a domain class, see referenced issue).

"hot" restarting the app initializes hibernate/gorm again resulting in a new `GrailsDomainBinder` instance and new hibernate metadata. however, `GrailsDomainBinder$CollectionType` still references the old/replaced `GrailsDomainBinder` along with the old/replaced hibernate metadata.

as CollectionType is already being instantiated only once per `GrailsDomainBinder` instance:  
https://github.com/grails/gorm-hibernate5/blob/v7.0.0/grails-datastore-gorm-hibernate5/src/main/groovy/org/grails/orm/hibernate/cfg/GrailsDomainBinder.java#L103-L107
it should be safe/without drawback to make the static `CollectionType` properties non-static.

pull-request follows (which fixes the problem for me locally at least..).

**Comment by graemerocher** [comment]
Thanks for the PR
