### ISSUE TITLE
Slowness of joining domain class vs. raw SQL query

### ISSUE THREAD

**Issue by gregopet** [grails/gorm-hibernate5#14]
I'm having an interesting performance issue at work where a GORM query takes orders of magnitude to complete than a plain SQL. A mapping table represented by a composite primary key domain class (without any `hasMany` or `belongsTo` relations) takes 2 seconds to load via GORM while `groovy.sql.Sql` takes around 50ms. The actual queries are practically identical in both cases (verified with the SQL logger), so no N+1 selects problem.

My main question is whether this difference

- is simply to be expected
- is caused by us because we're doing something suboptimal
- is a bug

I've simplified the case in a test app which I will upload somewhere (Github can't handle attachments apparently), but the gist of it is:

````
class Author implements DomainClass {
    Long id
    String name
}
````

````
class Book implements DomainClass {
    Long id
    String title
}
````

````
class BookAuthor implements DomainClass, Serializable{
    Book book
    Author author

	static mapping = {
		id composite:['book', 'author']
		version false
	}

	@Override
	boolean equals(other) {
		if (other instanceof BookAuthor) {
			other.author == author?.id && other.book == book?.id
		}
	}

    @Override
	int hashCode() {
		def builder = new HashCodeBuilder()
		if (author) builder.append(author.id)
		if (book) builder.append(book.id)
		builder.toHashCode()
	}
}
````

````
def index() {
        def authors = Author.findAll().groupBy { it.id }
        def books = Book.findAll().groupBy { it.id }


        long time = System.nanoTime();

        assert BookAuthor.findAll().size() == 7000
        long domainsLoadedAt = System.nanoTime()
        long timeOfDomainClassLoad = domainsLoadedAt - time;

        int itemsLoaded = 0
        new Sql(dataSource).eachRow("select author_id, book_id from book_author") { row ->
            assert authors.get(row.author_id)
            assert books.get(row.book_id)
            itemsLoaded++
        }
        assert itemsLoaded == 7000
        long timeOfPlainQuery = System.nanoTime() - domainsLoadedAt;

        render text: "Loaded BookAuthor domains in ${timeOfDomainClassLoad / 1000000.0}ms while query took ${timeOfPlainQuery / 1000000.0}ms"

    }
````

I also have a Bootstrap class that creates 500 Authors, 1500 Books and 7000 BookAuthors (this roughly matches the amounts of data we have in the real application).

Under Hibernate 4 the typical response is `Loaded BookAuthor domains in 1325.219786ms while query took 70.200815ms` while Hibernate 5 is giving me `Loaded BookAuthor domains in 844.710136ms while query took 20.408714ms`. We're using Postgres, not the in-mem database in reality, but it should not matter and the results look similar on both.

**Comment by gregopet** [comment]
I've uploaded the test app [here](https://dl.dropboxusercontent.com/u/1898992/join-table-slowness.zip)

**Comment by graemerocher** [comment]
Most likely reason is that because Hibernate is stateful and by calling `Book.findAll()` you are loading ever object in the database into memory, which causes memory strain on the application and slows it down. Whilst with the native query there is no state and hence no memory strain.

**Comment by gregopet** [comment]
True, I am creating 7000 objects vs. just streaming over the results, however (discounting Hibernate's meta data) those objects only contain 2 Longs. I tried inserting an additional row into the Sql `eachRow` block: `tupleList << new Tuple(authors.get(row.author_id), books.get(row.book_id))` produces almost no noticable slowdown.

If instead of that command I insert `new BookAuthor(author: authors.get(row.author_id), book: books.get(row.book_id))`, then both execution paths take nearly the same time, so it would appear either Hibernate or GORM are doing a lot of extra work when instantiating objects, be it memory or CPU-wise. 

Would it be a useful sanity check for GORM if I tried replicating this code in a pure Spring Boot & Hibernate application to see how plain Hibernate compares to GORM, or would I most probably be wasting my time?

**Comment by graemerocher** [comment]
Sure feel free.

**Comment by gregopet** [comment]
Vanilla Spring Boot behaves much better: `Loaded BookAuthor domains in 36.146774ms while SQL completed in 18.897018ms`

Here is my demo app: https://dl.dropboxusercontent.com/u/1898992/join-table-boot.zip

**Comment by graemerocher** [comment]
So the GORM example and the Boot/JPA example aren't equivalent as the latter uses a field access strategy (see https://docs.jboss.org/hibernate/orm/5.1/userguide/html_single/chapters/domain/access.html) instead of a property access strategy which accounts for the performance difference. In my tests when using field access the GORM the results for a large data set are:

      Loaded BookAuthor domains in 164.342229ms while query took 120.481056ms

Which is a much smaller margin of difference.

Property access is of course slower, since it uses reflection to invoke the setter which then sets the field. GORM doesn't currently allow you to alter this. I have added this possibility in the 6.0.x branch using:

    static mapping = {
        id composite:['book', 'author']
        version false
        book accessType: AccessType.FIELD
        author accessType: AccessType.FIELD
    }

It could actually be argued that field access should be the default, and we may consider that for GORM 6.1 now that the ability to customise it is possible.
