### ISSUE TITLE
Impossible to hot deploy to Websphere

### ISSUE THREAD

**Issue by leleFc** [grails/gorm-hibernate5#148]
I have a simple application created with Grails 3.3.10 (Gorm 6.1.12.RELEASE) with a single domain class.
When I try to hot deploy to IBM Websphere 8.5.5.13 (Java 8) I always fail with the error explained in the attached stacktrace (org.grails.orm.hibernate.proxy.GroovyAwareJavassistLazyInitializer: frozen class (cannot edit)).
If I stop and restart WAS, my application starts correctly, but if I stop my application and I try to restart, the error happens again.
I think my issue is similar to this one: https://github.com/grails/gorm-hibernate5/issues/74

PS: my application use Javassist 3.18.2-GA as shared library
[stacktrace_gorm.txt](https://github.com/grails/gorm-hibernate5/files/3526148/stacktrace_gorm.txt)

**Comment by leleFc** [comment]
Closed because it was related to a WAS class loader problem

**Comment by ernesto-castelan** [comment]
How did you solve the issue? Did you change some configuration in WebSphere?

**Comment by leleFc** [comment]
In my case there was a problem with Javassit version shipped with WAS, so I created a shared library with "javassist-3.18.2-GA.jar" and I linked it to my application, after that I changed the class loader policy to "Class loaded with local class loader first (parent last)".
I hope it may help you.
