### ISSUE TITLE
Update hibernate version

### ISSUE THREAD

**Issue by demon101** [grails/gorm-hibernate5#165]
Now version 5.4.2 of hibernate-core used in grails 4
It can be updated to 5.4.10. 
By the update, issue  https://github.com/grails/grails-data-mapping/issues/1212   will be fixed by https://hibernate.atlassian.net/browse/HHH-8091

and duplicated 
https://github.com/grails/grails-data-mapping/issues/1160
https://github.com/grails/grails-core/issues/9352
https://github.com/grails/grails-core/issues/630
https://github.com/grails/grails-core/issues/7801

**Comment by puneetbehl** [comment]
Updated with commit https://github.com/grails/gorm-hibernate5/commit/5b3a0e177111be65087648fe726d9f88df37ef82
