### ISSUE TITLE
6.0.5 - HibernateConnectionSourceSettings.HibernateSettings not correctly initialized

### ISSUE THREAD

**Issue by zyro23** [grails/gorm-hibernate5#17]
trying to use `application.yml`
```groovy
hibernate:
    configClass: foo.bar.MyHibernateMappingContextConfiguration
```
in a grails 3.2.4 (gorm-6.0.5) app, that still resulted in default `HibernateMappingContextConfiguration` being configured.

debugging to https://github.com/grails/gorm-hibernate5/blob/v6.0.5/grails-datastore-gorm-hibernate5/src/main/groovy/org/grails/orm/hibernate/connections/HibernateConnectionSourceFactory.java#L92 you can see that:
* `HibernateConnectionSourceSettings.HibernateSettings` is populated as a map correctly, containing the entrySet ["configClass": "foo.bar.MyHibernateMappingContextConfiguration"], but
* `HibernateConnectionSourceSettings.HibernateSettings.configClass` property is `null` (which is returned by `hibernateSettings.getConfigClass()`).

so i guess there is something missing with the initialization that sets (or rather not sets) the `HibernateSettings` properties?

**Comment by graemerocher** [comment]
I committed a test for this and it seems to work fine for me. Not sure why you are seeing this issue.

**Comment by zyro23** [comment]
thanks for the test. got it working now. after all, it seems there was a naming mismatch of my config entry vs. the actual class name. as usual, your support is really much appreciated!
