### ISSUE TITLE
7.1.0.M3 Release is not published

### ISSUE THREAD

**Issue by arixmkii** [grails/gorm-hibernate5#251]
So, all builds with Grails 4.1.0.M3 will fail with
```
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve org.grails.plugins:hibernate5:7.1.0.M3.
     Required by:
         project :
      > Could not resolve org.grails.plugins:hibernate5:7.1.0.M3.
```

**Comment by transentia** [comment]
Can confirm.

Downloaded grails-4.1.0.M3.zip, then:

```
PS C:\Users\Bob\Desktop\grails-4.1.0.M3\bin> & .\grails.bat create-app fred
| Application created at C:\Users\Bob\Desktop\grails-4.1.0.M3\bin\fred
PS C:\Users\Bob\Desktop\grails-4.1.0.M3\bin> cd fred
PS C:\Users\Bob\Desktop\grails-4.1.0.M3\bin\fred> & .\grailsw.bat run-app
| Resolving Dependencies. Please wait...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'fred'.
> Could not resolve all files for configuration ':runtimeClasspath'.
   > Could not resolve org.grails.plugins:hibernate5:7.1.0.M3.
     Required by:
         project :
      > Could not resolve org.grails.plugins:hibernate5:7.1.0.M3.
         > Could not get resource 'https://oss.jfrog.org/oss-snapshot-local/org/grails/plugins/hibernate5/7.1.0.M3/hibernate5-7.1.0.M3.pom'.
            > Could not GET 'https://oss.jfrog.org/oss-snapshot-local/org/grails/plugins/hibernate5/7.1.0.M3/hibernate5-7.1.0.M3.pom'. Received status code 409 from server:

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

CONFIGURE FAILED in 16s
| Error Error initializing classpath: Could not GET 'https://oss.jfrog.org/oss-snapshot-local/org/grails/plugins/hibernate5/7.1.0.M3/hibernate5-7.1.0.M3.pom'. Received status code 409 from server:  (Use --stacktrace to see the full trace)
PS C:\Users\Bob\Desktop\grails-4.1.0.M3\bin\fred>
```

Looked around jfrog, didn't find the requisite files.

**Comment by puneetbehl** [comment]
Yes, the version 7.1.0.M3 was not released earlier due to some issues. But, it should be fixed now.

**Comment by arixmkii** [comment]
@puneetbehl 
Something is wrong with the build I think
```
* What went wrong:
A problem occurred configuring root project 'tts-web'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find io.micronaut:micronaut-inject-groovy:.
     Required by:
         project : > org.grails.plugins:hibernate5:7.1.0.M3
```
It can't understand which version of `micronaut-inject-groovy` to take.

**Comment by puneetbehl** [comment]
Please share a sample application

**Comment by puneetbehl** [comment]
The reason you noticed the error earlier was because Grails 4.1.0.M3 is released with BOM point to GORM Hibernate5 7.1.0.M3 which was not released earlier. 

Please note that the same error would happen with GORM MongoDB and Neo4j. I am in process of releasing the same.

**Comment by arixmkii** [comment]
I will check the app and if I can reproduce it with any reasonable sample. Thank you for your work.

**Comment by puneetbehl** [comment]
https://github.com/puneetbehl/testapp-4.1.0.M3/

**Comment by arixmkii** [comment]
@puneetbehl I checked your app. You have M2 in classpath here https://github.com/puneetbehl/testapp-4.1.0.M3/blob/main/build.gradle#L8

If you change it to M3, you will get the same error I have.

**Comment by transentia** [comment]
In my real project, I found I could completely remove:

        classpath "org.grails.plugins:hibernate5:7.1.0.M2"

from the buildscript.dependencies section with no effect on the project. Can't see why the build needs this(?)

Otherwise, M3 is working for me. Thanks.

**Comment by puneetbehl** [comment]
The classpath section is there for the Gradle scrips like schemaExport. I found the problem and will push a fix soon. Meanwhile, I created another issue to track the problem with 7.1.0.M3 in the classpath. 

Thanks!
