### ISSUE TITLE
7.1.0.M3 Could not resolve all artifacts for configuration ':classpath'.

### ISSUE THREAD

**Issue by puneetbehl** [grails/gorm-hibernate5#253]
```
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find io.micronaut:micronaut-inject-groovy:.
     Required by:
         project : > org.grails.plugins:hibernate5:7.1.0.M3
```

https://github.com/puneetbehl/testapp-4.1.0.M3/

Ref: #251

**Comment by arixmkii** [comment]
- jdk 11.0.9 adoptopenjdk hs
- gradle 6.8
- grails 4.1.0.M4

with 7.1.0.M4 in build classpath (`classpath "org.grails.plugins:hibernate5:7.1.0.M4"`) there is an error during build
```
   > Class org.codehaus.groovy.ast.ModuleNode does not implement the requested interface org.codehaus.groovy.ast.NodeMetaDataHandler
```

Different from before, but still a no go. 7.1.0.M2 works ok.
