### ISSUE TITLE
groovy.lang.MissingMethodException: No signature of method: grails.orm.bootstrap.HibernateDatastoreSpringInitializer

### ISSUE THREAD

**Issue by avaneeshGit** [grails/gorm-hibernate5#269]
Hi @puneetbehl , I am still getting this error even i do have gormVersion=7.0.4.RELEASE.
Here is build.gradle:
grailsVersion=4.0.8
gorm.version=7.0.4.RELEASE
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.jvmargs=-Dfile.encoding=UTF-8 -Xmx1024M

**Comment by avaneeshGit** [comment]
@puneetbehl

**Comment by puneetbehl** [comment]
Not enough information
