### ISSUE TITLE
dependencies 6.0.9 resolving hibernate 5.0.11.Final

### ISSUE THREAD

**Issue by bdbogjoe** [grails/gorm-hibernate5#27]
using grails 3.2.7

- created empty plugin using grails create-plugin command
- adding dependency compile "org.grails.plugins:hibernate5"

if i check with gradle dependencies, seems hibernate 5.0.11 is resolved

https://github.com/bdbogjoe/grails-gorm-hibernate-dep-issue

**Comment by graemerocher** [comment]
This is Spring Boot enforcing the default set of dependencies, use an explicit version.

**Comment by bdbogjoe** [comment]
to change hibernate version in your build.gradle : 

ext['hibernate.version'] = '5.1.3.Final'
