### ISSUE TITLE
NPE at startup with Hibernate 5.4.29 and "version false" domain classes

### ISSUE THREAD

**Issue by alanwilkie-finocomp** [grails/gorm-hibernate5#270]
Hibernate has made a change between 5.4.28 and 5.4.29 that adds some convenience methods to the `OptimisticLockingStyle` enum. Consequently, it expects that the optimistic locking style for each entity is always set to a proper value. `GrailsDomainBinder` currently only calls `setOptimisticLockingStyle` if the domain class has a `version` property.

It's arguable whether it's a GORM issue or a Hibernate issue (it seems a bit rough to make a breaking change to the behaviour in a 0.0.1 release), but it's not too hard to fix in GORM.

**Comment by aulea** [comment]
Duplicate of #265

**Comment by alanwilkie-finocomp** [comment]
Thanks @aulea, I'll close this one.
