### ISSUE TITLE
BROKEN >= 7.0.4 Causes Resource Controllers to Render as Content-Type: application/xhtml

### ISSUE THREAD

**Issue by codeconsole** [grails/gorm-hibernate5#303]
Changing a working app from 

`implementation "org.grails.plugins:hibernate5:7.0.3`

to any version >= 7.0.4 results in Resources controllers rendered as:

Content-Type: application/xhtml+xml;charset=UTF-8

and the browser no longer displays them properly.

Using any version <= 7.0.3 results in controllers rendering pages as

Content-Type: text/html;charset=UTF-8

What changed with this plugin between 7.0.3 to 7.0.4 that affected choosing the correct mime type??

https://github.com/grails/grails-data-mapping/compare/v7.0.3..v7.0.4

https://github.com/grails/grails-data-mapping/compare/v7.0.3..7.0.4

And which tag represent 7.0.4 that is in https://repo.grails.org/grails/core/org/grails/plugins/hibernate5/7.0.4/ ?

**Comment by codeconsole** [comment]
Update:
I checked out this code.  I built and used the 7.0.3 jar:
```
    implementation rootProject.files('lib/hibernate5-7.1.0.jar')
    implementation "org.grails:grails-datastore-gorm-hibernate5:7.0.5"
```
Verified WORKING

 I built and used the 7.0.4 jar:
```
    implementation rootProject.files('lib/hibernate5-7.0.4.jar')
    implementation "org.grails:grails-datastore-gorm-hibernate5:7.0.5"
```
Verified NOT WORKING 

I built a jar using the latest on the 7.0.x branch
```
    implementation rootProject.files('lib/hibernate5-7.0.6.jar')
    implementation "org.grails:grails-datastore-gorm-hibernate5:7.0.5"
```
Verified NOT WORKING 

Using the latest 7.0.x branch, I made the following changes

index bf7d02c..0729ec1 100644
--- a/grails-plugin/src/main/groovy/grails/orm/bootstrap/HibernateDatastoreSpringInitializer.groovy
+++ b/grails-plugin/src/main/groovy/grails/orm/bootstrap/HibernateDatastoreSpringInitializer.groovy
@@ -17,6 +17,7 @@ package grails.orm.bootstrap
 import groovy.transform.CompileStatic
 import groovy.util.logging.Slf4j
 import org.grails.datastore.gorm.bootstrap.AbstractDatastoreInitializer
+import org.grails.datastore.gorm.bootstrap.support.ServiceRegistryFactoryBean
 import org.grails.datastore.gorm.jdbc.connections.CachedDataSourceConnectionSourceFactory
 import org.grails.datastore.gorm.support.AbstractDatastorePersistenceContextInterceptor
 import org.grails.datastore.mapping.config.DatastoreServiceMethodInvokingFactoryBean
@@ -161,20 +162,12 @@ class HibernateDatastoreSpringInitializer extends AbstractDatastoreInitializer {
                 bean.primary = true
             }
             autoTimestampEventListener(hibernateDatastore:"getAutoTimestampEventListener")
+            "hibernateDatastoreServiceRegistry"(ServiceRegistryFactoryBean, ref("hibernateDatastore"))
             getBeanDefinition("transactionManager").beanClass = PlatformTransactionManager
             hibernateDatastoreConnectionSourcesRegistrar(HibernateDatastoreConnectionSourcesRegistrar, dataSources)
             // domain model mapping context, used for configuration
             grailsDomainClassMappingContext(hibernateDatastore:"getMappingContext")
 
-            loadDataServices(null)
-                    .each {serviceName, serviceClass->
-                        "$serviceName"(DatastoreServiceMethodInvokingFactoryBean) {
-                            targetObject = ref("hibernateDatastore")
-                            targetMethod = 'getService'
-                            arguments = [serviceClass]
-                        }
-                    }

```
    implementation rootProject.files('lib/hibernate5-7.0.6-NEW.jar')
    implementation "org.grails:grails-datastore-gorm-hibernate5:7.0.5"
```

Verified WORKING

I then checked out master and applied those same changes to master
```
    implementation rootProject.files('lib/hibernate5-7.1.0.jar')
    implementation "org.grails:grails-datastore-gorm-hibernate5:7.1.0.RC1"
```

Therefore, the following code is 100% causing the issue:
```
-            loadDataServices(null)
-                    .each {serviceName, serviceClass->
-                        "$serviceName"(DatastoreServiceMethodInvokingFactoryBean) {
-                            targetObject = ref("hibernateDatastore")
-                            targetMethod = 'getService'
-                            arguments = [serviceClass]
-                        }
-                    }
```

Perhaps it is changing the loading of services which is overwriting the mime types that are available?  I have no idea.  All I know is it works when that code is reverted to

```
+            "hibernateDatastoreServiceRegistry"(ServiceRegistryFactoryBean, ref("hibernateDatastore"))
```

**Comment by codeconsole** [comment]
Sample App that replicates

https://github.com/codeconsole/gormbug

**Comment by puneetbehl** [comment]
@codeconsole Thank you for the great debugging effort, I will look into this soon.

**Comment by codeconsole** [comment]
@puneetbehl I've updated the sample to 5.0.0.RC1 https://github.com/codeconsole/gormbug

**Comment by codeconsole** [comment]
https://github.com/grails/grails-core/issues/12057

**Comment by puneetbehl** [comment]
@codeconsole Did you see this issue in Grails 4? if yes, could you please share a sample application? I am not able to replicate it with Grails 4.

**Comment by codeconsole** [comment]
@puneetbehl It's not in Grails 4. Only Grails 5.   It has nothing to do with that mentioned issue. Sorry for linking that to the ticket.

**Comment by puneetbehl** [comment]
I think it might be related to the same underline issue. But, let me verify.

**Comment by codeconsole** [comment]
@puneetbehl I noticed it when I upgraded from Grails 4.x to Grails 5.x.   Would you like me to create a 4.x sample app to verify?

**Comment by puneetbehl** [comment]
Yes, please share a 4.0.x sample application.

**Comment by codeconsole** [comment]
Grails 4.0.12 - Confirmed not working.  
https://github.com/codeconsole/gormbug/tree/4.0.x
```
git clone https://github.com/codeconsole/gormbug
git checkout 4.0.x
./gradlew bootWar
java -jar build/libs/gormbug-1.6.8.war
```

**Comment by codeconsole** [comment]
@puneetbehl I can confirm using 7.1.0-SNAPSHOT on 5.0.0.RC3 fixes the issue.  Out of curiosity, why was it affecting the mime types?
