### ISSUE TITLE
gorm unique Constraints throw exception?

### ISSUE THREAD

**Issue by xp13910818313** [grails/gorm-hibernate5#32]
using gorm-hibernate5-spring-boot 6.0.7.RELEASE & grails-datastore-gorm 6.0.7.RELEASE in spring boot project.
application.yml config: 
```
grails.gorm.failOnError: false
grails.gorm.autoFlush: false
```
Domain class :
```
@Entity
class Book implements GormEntity<Book> {
    String title
    static constraints = {
        title (nullable: false,size: 0..200, unique: true, blank:false)
    }
}
```
controller : 
```
        def book1=new Book(title: "one");
        book1.save()
        def book2=new Book(title: "one");
        book2.save()
        println book2.errors
```
application throw exception:
```
org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: "UK_G0286AG1DLT4473ST1UGEMD0M_INDEX_1 ON PUBLIC.BOOK(TITLE) VALUES (STRINGDECODE('one'), 1)"; SQL statement:
insert into book (id, version, title) values (null, ?, ?) 
```

why? please help me.

**Comment by xp13910818313** [comment]
if using Grails3.2.8， book2.errors contains the error ：
org.grails.datastore.mapping.validation.ValidationErrors: 1 errors
`Field error in object 'com.demo.data.Book' on field 'title': rejected value [One];default message [Property [{0}] of class [{1}] with value [{2}] must be unique]`
Why there are different behaviors using GORM between in spring boot and grails ？

**Comment by graemerocher** [comment]
Try change

```
def book1=new Book(title: "one");
        book1.save()
```

To

```
def book1=new Book(title: "one");
        book1.save(flush:true)
```

**Comment by xp13910818313** [comment]
Thanks, but it doesn't work.
neithor save(flush:true) nor save(validate:true,flush:true) .

**Comment by graemerocher** [comment]
I have written a test for this and cannot reproduce. Please provide an example that reproduces the issue.

**Comment by xp13910818313** [comment]
By way of upgrading gorm to 6.1.2 fix it. 
my pom file:
```
		<dependency>
			<groupId>org.grails</groupId>
			<artifactId>gorm-hibernate5-spring-boot</artifactId>
			<version>6.1.2.RELEASE</version>
		</dependency>
		<dependency>
			<groupId>org.grails</groupId>
			<artifactId>grails-datastore-gorm</artifactId>
			<version>6.1.2.RELEASE</version>
		</dependency>
```

**Comment by xp13910818313** [comment]
graemerocher,sorry.
here is the example code. 
[demo.zip](https://github.com/grails/gorm-hibernate5/files/975698/demo.zip)

**Comment by graemerocher** [comment]
The sample project doesn't compile for me.

```
le) on project demo: Compilation failure: Compilation failure: 
[ERROR] /Users/graemerocher/grails/apps/unique-demo/QuestionDemo2/target/generated-sources/groovy-stubs/main/com/example/controller/BookController.java:[10,89] package org.springframework.transaction.annotation does not exist
[ERROR] /Users/graemerocher/grails/apps/unique-demo/QuestionDemo2/target/generated-sources/groovy-stubs/main/com/example/domain/Book.java:[39,67] cannot find symbol
[ERROR]   symbol:   class D
[ERROR]   location: class com.example.domain.Book
[ERROR] /Users/graemerocher/grails/apps/unique-demo/
```

**Comment by xp13910818313** [comment]
@graemerocher , it's in spring-tx.4.3.8.RELEASE.jar,base on grails-datastore-gorm.6.0.9.RELEASE
![demo1](https://cloud.githubusercontent.com/assets/11690092/25699278/26115712-30f5-11e7-9be3-77dd1b1c7edb.png)

**Comment by graemerocher** [comment]
Provide an example that works and we can take a look. We're not here to diagnose non-functioning examples.

**Comment by xp13910818313** [comment]
@graemerocher ，please check this example . 


[uniqueDemo.zip](https://github.com/grails/gorm-hibernate5/files/976632/uniqueDemo.zip)

**Comment by xp13910818313** [comment]
upgrading gorm to 6.1.2 could fix this.
 pom file:
```
		<dependency>
			<groupId>org.grails</groupId>
			<artifactId>gorm-hibernate5-spring-boot</artifactId>
			<version>6.1.2.RELEASE</version>
		</dependency>
		<dependency>
			<groupId>org.grails</groupId>
			<artifactId>grails-datastore-gorm</artifactId>
			<version>6.1.2.RELEASE</version>
		</dependency>
```
if using grails.persistence.Entity annotation in domain class , should add dependencies in pom file:
```
		<dependency>
			<groupId>org.grails</groupId>
			<artifactId>grails-core</artifactId>
			<version>3.2.8</version>
		</dependency>
		<dependency>
			<groupId>org.grails</groupId>
			<artifactId>grails-bootstrap</artifactId>
			<version>3.2.8</version>
		</dependency>
		<dependency>
			<groupId>org.yaml</groupId>
			<artifactId>snakeyaml</artifactId>
			<version>1.17</version>
		</dependency>
```
i do't know why, but it's strange dependencies .
