### ISSUE TITLE
Setting schema per datasource not possible

### ISSUE THREAD

**Issue by marcowi** [grails/gorm-hibernate5#35]
Grails 3.2.8
Gorm 6.0.9 & 6.1.1
Gradle 2.9
Java 1.8

Having multiple datasources with different schemes it is not possible to set a default_schema for each datasource.

plugin.groovy or application.groovy:
`hibernate {
   default_schema = "schema1"
}
hibernate_second {
   default_schema = "schema2"
}`

when using a domain from the second datasource you get: "schema1 does not exist"

**Comment by graemerocher** [comment]
The syntax has changed in GORM 6.x. Now the Hibernate settings should be nested below the named data source. Example:

```
dataSources:
    foo:
        hibernate:
             default_schema: schema1
```

An example of the syntax can be seen at http://gorm.grails.org/latest/hibernate/manual/index.html#multipleDataSources

**Comment by marcowi** [comment]
It does not work if you configure it like that in a plugin.groovy of a plugin. It does recognize the hibernate settings if they are the "old" style though (except for the schema).
As a workaround we configure the schema in the domain class itself which is probably better anyway.
