### ISSUE TITLE
Unique Constraint/Primary Key Validation issue

### ISSUE THREAD

**Issue by KerchumA222** [grails/gorm-hibernate5#36]
### Steps to Reproduce

1. Clone repo
2. Run integration tests

### Expected Behaviour

There should be a validation error (not unique).

### Actual Behaviour

On calling `save` or `insert` exception: `A different object with the same identifier value was already associated with the session org.springframework.dao.DuplicateKeyException`
On calling `validate` returns true, even though unique constraint is violated.

### Environment Information

- **Operating System**: Windows
- **Grails Version:** 3.2.9
- **JDK Version:** 1.8

### Example Application

https://github.com/KerchumA222/UniqueFailure
There are integration tests that express intended behavior.

**Comment by graemerocher** [comment]
Seems to work fine in 6.1.x, see test above
