### ISSUE TITLE
Using Map/PropertyResolver for standalone GORM does not work as per documentation

### ISSUE THREAD

**Issue by ysb33r** [grails/gorm-hibernate5#4]
The documentation states that a `HibernateDatastore` can be constructed via a Map or PropertyResolver:

```groovy
Map configuration = [
    'hibernate.hbm2ddl.auto':'create-drop',
    'dataSource.url':'jdbc:h2:mem:myDB'
]
HibernateDatastore datastore = new HibernateDatastore( configuration, Person)
```

But this does not work. The above code will fail to compile. If the `Map` is type-casted to a `PropertyResolver` initialisation eventually result in a `UnsupportedOperationException`. Not using the class-array constructor as in the  [ExampleSpec](https://github.com/grails/gorm-hibernate5/blob/91461ef14a80086d74a975c4416a1e6e079b4384/examples/standalone-hibernate5/src/test/groovy/org/grails/hibernate/example/ExampleSpec.groovy) code will initialise correctly, but obviously the ability to configure H2 via a Map (or using a different JDBC URL) is lost. 

P.S. The fact that the doc was done from handcrafted code did not help. It would be better to include a code snippet from the examples directory.

**Comment by graemerocher** [comment]
For the moment you can call `DatastoreUtils.createPropertyResolver(configuration)` and that will resolve your issue

**Comment by ysb33r** [comment]
Thanks @graemerocher. I discovered that after a while. I think it would be worthwhile to have the Map constructor in gom-hibernate in a similar fashion as to gorm-neo4j.

**Comment by graemerocher** [comment]
Agreed, will look to add it. Thanks for the feedback.
