### ISSUE TITLE
Second level cache not working for inherited domains

### ISSUE THREAD

**Issue by purpleraven** [grails/gorm-hibernate5#484]
After upgrade from 3.3.14 to 4.0.13 I have found an issue with hibernate second level cache for entities with inheritance.
It stop working in Gorm version: 7.0.8.RELEASE
Before, for version 6.1.12.RELEASE if works well

The bug can be reproduced in application:

https://github.com/purpleraven/grails-4-inheritance-cache-bug

On first request to '/' 
On every request to http://localhost:8080 two entity loaded from DB
```
        Test.get(1l)
        TestAA.get(1l)
```
Both of them with enabled cache, TestAA is inherited from TestA

On first  request we can see two DB queries in the log
on following requests we can see only one query (0 queries expected) 

![DeepinScreenshot_select-area_20220114212848](https://user-images.githubusercontent.com/20344446/149581212-f83a551a-1360-4170-ac77-807d24e0c139.png)

Cache on parent class also not working.

I can try to do a troubleshooting, but any breadcrumbs is required. 
Thx

P.S.
The bug is a root cause for performance degradation for one of apps after upgrade gfrom grails 3 to grails 4
https://stackoverflow.com/questions/56072860/grails-3-vs-4-performance-starting-time-and-memory/70704221#70704221

**Comment by puneetbehl** [comment]
There will not be any 7.1.x release. And, we normally merge 7.0.x to latest default branch.
