### ISSUE TITLE
Continuation to #62

### ISSUE THREAD

**Issue by vishwanath-openprise** [grails/gorm-hibernate5#65]
In continuation to issue #62 

@graemerocher within same transaction, session, if an object is updated and saved (irrespective whether it is flushed or not) if we query for the same object we should be able to get the dirty instance back. Right?

My understanding:

For get, load within the same transaction: We look at session first, if not found then second level cache if not found then hit DB to retrieve it.
For queries: We hit DB first and retrieve the list and then include/update matching objects from second level cache and then from current session.
I validated this understanding with spring-hibernate(5) project and it looks to be valid.
In fact I tried with grails 3.2.9 - and works there too. But not in grails 3.3.1

Does grails, gorm work differently?

Spring-hiberbnate:
User n = new User();
n.setName(name);
n.setEmail(email);
Session session = sessionFactory.getCurrentSession();
session.save(user);
Criteria c = session.createCriteria(User.class);
c.add(Restrictions.eq("name", user.getName()));
List results = c.list();
System.out.println("Size: " + results.size());

grails-gorm (Works in 3.2.9, but not in 3.3.1):
TestObject o = new TestObject()
o.name = "name_here"
o.description = "desc_here"
o.save()
println "START createCriteria--------------"
def c = TestObject.createCriteria()
def results = c.list {
eq("name", o.name)
}
results?.each {
println it.name + " " + it.description
}
println "END createCriteria--------------"

**Comment by graemerocher** [comment]
Depending on ID generation strategy a call to save() may or may not be persisted to the database. Calling `save()` does not automatically result in a database insert, so the state of the transaction is irrelevant. Without `flush:true` the data may not have been synchronised with the transaction.

Please stop repeating and opening the same issues. We have a slack for a reason for these types of questions. This question could and should have been asked in the original issue report or on Slack.
