### ISSUE TITLE
Release 8.0.0 depends on grailsVersion 6.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by mluckam** [grails/gorm-hibernate5#752]
Is 6.0.0-SNAPSHOT the desired version of grails to depend on or was this an oversight?  Building a project with a dependency on `org.grails.plugins:hibernate5:8.0.0` it appears that `grails-bom-6.0.0-SNAPSHOT.pom` is not in maven central.

```
./gradlew clean build

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':installmanager-api'.
> Could not resolve all files for configuration ':installmanager-api:classpath'.
   > Could not resolve org.grails.plugins:hibernate5:8.0.0.
     Required by:
         project :installmanager-api
      > Could not resolve org.grails.plugins:hibernate5:8.0.0.
         > Could not parse POM https://repo.maven.apache.org/maven2/org/grails/plugins/hibernate5/8.0.0/hibernate5-8.0.0.pom
            > Could not find org.grails:grails-bom:6.0.0-SNAPSHOT.
              Searched in the following locations:
                - https://repo.maven.apache.org/maven2/org/grails/grails-bom/6.0.0-SNAPSHOT/maven-metadata.xml
                - https://repo.maven.apache.org/maven2/org/grails/grails-bom/6.0.0-SNAPSHOT/grails-bom-6.0.0-SNAPSHOT.pom

```
https://github.com/grails/gorm-hibernate5/blob/v8.0.0/gradle.properties#L30C1-L30C29

**Comment by matrei** [comment]
After reviewing this I see that there is a comment in gradle.properties above the grailsVersion declaration:
```
# Following are used only for example projects
...
grailsVersion=6.0.0-SNAPSHOT
...
```
So this should probably not be in the published artifact. grails-data-mapping uses https://raw.githubusercontent.com/grails/grails-common-build/master/common-publishing.gradle which removes the dependencyManagement node from the POM. Is that what is missing here?
