### ISSUE TITLE
[Bug]: Invalid update of `LAST_UPDATED` prop

### ISSUE THREAD

**Issue by tkvw** [grails/gorm-hibernate5#76]
Not sure if this is actually used, but this code assumes that the `LAST_UPDATED` property is of type `java.util.Date`, so this will error if another type is used.  
https://github.com/grails/gorm-hibernate5/blob/10b4cd4f609a685bd7f5568cf7273e8ddf2eb665/grails-datastore-gorm-hibernate5/src/main/groovy/org/grails/orm/hibernate/HibernateSession.java#L128-L131

**Comment by jameskleeh** [comment]
@tkvw Can you create an example project that demonstrates the issue?

**Comment by tkvw** [comment]
@jameskleeh : No, not really. I was searching the sources for `LAST_UPDATED` (unrelated) and came across this snippet. As the `AutoTimestampEventListener` of `GORM` uses the `timestampProvider` to initialize the correct type I thought this could lead to unexpected behaviour (without actually experienced it). This snippet simply assigns a Date instance, which is potentially dangerous I think.

**Comment by jameskleeh** [comment]
@tkvw This was fixed already in the 6.0.x branch. I just merged it to 6.1.x
