### ISSUE TITLE
Multitenant - Discriminator - @CurrentTenant not honored if session created by SessionFactory.currentSession

### ISSUE THREAD

**Issue by jdaugherty** [grails/gorm-hibernate5#781]
**Description:**
If a hibernate session has not yet been used for the current thread, and `sessionFactory.currentSession` is invoked, the tenant will not be honored.  If `Author.withSession { Session session ->  }` is invoked first, then `sessionFactory.currentSession` will honor the tenant. 

**Affected Versions**
My issue was originally found in a Grails 5.x project, but given that Grails 6.x has been released, I reproduce it in Grails 6.x as well.

**Sample project:**  
Generated a Grails 6 project, setup discriminator based multitenant config, added an Author domain class, create two Authors with opposite tenants in BootStrap, added service demonstrating the problem, and added a test case for service.

[https://github.com/jdaugherty/multitenant-issue](https://github.com/jdaugherty/multitenant-issue )

**Run the integration tests to reproduce:** 
` gradle integrationTest`

**Comment by Goliath** [comment]
@jdaugherty IMO that's correct behavior, as `sessionFactory.currentSession` is returning non tenant, default sessionFactory.
If I correctly remember you should use sth like:

```
sessionFactory = hibernateDatastore.getDatastoreForConnection(Tenants.currentId()).getSessionFactory()
```

hope that helps.

**Comment by jdaugherty** [comment]
Thank you @Goliath.  This behavior is frustrating:

- If the session is already initialized, `sessionFactory` returns a session that works as expected.
- A Grails plugin / library that uses hibernate can unexpectedly expose this behavior.
- Grails is built upon Spring Boot so existing code that is written for Spring usually works.  In this case, non-Grails code could create a session and thus silently fail.

Hibernate documents how to create [custom sessions](https://docs.jboss.org/hibernate/orm/5.0/topical/html/sessionfactory/CustomSessionFactory.html).  The GORM guide mentions the `HibernateConnectionSourceFactory` as how it creates a `SessionFactory` which implies that `sessionFactory` should work.  This defect should at least be documented in the guide or be fixed to be consistent in Grails & non-Grails code.

**Comment by Goliath** [comment]
For completeness here are GORM docs describing above: 
https://gorm.grails.org/latest/hibernate/manual/index.html#_multi_tenancy_and_the_session_factory

**Comment by jdaugherty** [comment]
Thank you!
