### ISSUE TITLE
application.groovy in standalone mode is not read

### ISSUE THREAD

**Issue by injecteer** [grails/gorm-hibernate5#796]
As [per ref-doc](https://gorm.grails.org/latest/hibernate/manual/index.html#_the_default_mapping_constraints) one can include the `src/main/resources/application.groovy` to define the default mappings for all domain classes,

Although, the file is ignored if used in standalone mode in the code like so:
```
new HibernateDatastore( config, classes as Class[] )
```
Is there any way to include the default mappings from the file into the setup?

See also [the SO question](https://stackoverflow.com/questions/77600223/apply-application-groovy-in-gorm-standalone) for further details

**Comment by guillermocalvo** [comment]
@injecteer Could you please provide an example app that exhibits the behavior you observe?

**Comment by injecteer** [comment]
@guillermocalvo I created a [small repro](https://github.com/injecteer/gorm-repro-796) depicting the case.

**Comment by guillermocalvo** [comment]
Hi @injecteer. Thanks for providing a sample app; I can see now what you mean.

What you are describing is normal behavior: `application.groovy` will be ignored when `HibernateDatastore` is used standalone.

This is documented in [chapter 4 of the manual](https://gorm.grails.org/latest/hibernate/manual/index.html#configuration):

> GORM for Hibernate can be configured with:
> - the `grails-app/conf/application.yml` file ***when using Grails***,
> - the `src/main/resources/application.yml` file ***when using Spring Boot***
> - or by passing a `Map` or instanceof the `PropertyResolver` interface ***when used standalone***.

Going back to your example, you could make it work by adding `grails.gorm.default.mapping` to your config map:

```groovy
Map config = [
  'dataSource.driverClassName': 'org.h2.Driver',
  'dataSource.url':'jdbc:h2:mem:myDB;DB_CLOSE_DELAY=-1',
  'hibernate.hbm2ddl.auto':'create-drop',
  'grails.gorm.default.mapping': {
    version false
  },
]
```

I hope this solution helps you apply default mappings in your tests.

**Comment by injecteer** [comment]
@guillermocalvo would it work, if I put that `grails.gorm.default.mapping` group into the `application.yml`?

**Comment by guillermocalvo** [comment]
@injecteer 

> would it work, if I put that `grails.gorm.default.mapping` group into the `application.yml`?

No, it wouldn't. When `HibernateDatastore` is used standalone, the only configuration it gets is the one you pass to the constructor.

**Comment by injecteer** [comment]
@guillermocalvo 

How can I use the `src/main/resources/application.groovy` instead of the Map as the configuration of `HibernateDatastore`?

What the content of `application.groovy` should look like?

Any examples of those?

TIA

**Comment by guillermocalvo** [comment]
@injecteer

> How can I use the `src/main/resources/application.groovy` instead of the Map as the configuration of `HibernateDatastore`?

Sorry, I'm afraid you can't use it. When you invoke the constructor directly, you must provide a `Map` or a `PropertyResolver`.

**Comment by puneetbehl** [comment]
I think you could manually read configurations from the `application.groovy` or `application.yml` file and then pass it to the constructor. Please check example at https://github.com/grails/gorm-hibernate5/blob/8.0.x/grails-plugin/src/main/groovy/grails/test/hibernate/HibernateSpec.groovy

**Comment by injecteer** [comment]
I ended up with the following setup:
`application.yml`
```
gorm:
  dataSource:
    url: jdbc:h2:file:c:/db/demo-db
    driverClassName: org.h2.Driver
  hibernate:
    hbm2ddl.auto: update
```
the code:
```
static MAPPING = {
  id column:'o_id'
  version 'ch_id'
  lastUpdated column:'upd'
}

Map config = (Map)new YamlSlurper().parse( getClass().getResourceAsStream( '/application.yml' ) )

config.gorm[ 'grails.gorm.default.mapping' ] = MAPPING // <- custom mapping injection

new HibernateDatastore( config.gorm, classes as Class[] )
```
