### ISSUE TITLE
Startup error when using Spring Boot and GORM for Hibernate

### ISSUE THREAD

**Issue by waimun** [grails/gorm-hibernate5#82]
Steps to reproduce:

1. Go to https://start.spring.io and generate a project.
2. Select "Generate a gradle project with groovy and spring boot 2.0.0"
3. Leave default for group and artifact fields.
4. Under dependencies, select "web, actuator, and mysql"
5. Click generate button to download the project as a zip file. Unzip the file.
6. Modify build.gradle according to instructions for using GORM with Spring Boot: http://gorm.grails.org/latest/hibernate/manual/index.html#springBoot
#### The lines to be added to build.gradle is here for reference:

```
compile("org.grails:gorm-hibernate5-spring-boot:6.1.9.RELEASE")
compile "org.hibernate:hibernate-core:5.1.0.Final"
compile "org.hibernate:hibernate-ehcache:5.1.0.Final"
//runtime "com.h2database:h2:1.4.192"
// for MySQL
runtime "mysql:mysql-connector-java"

// for connection pooling
runtime "org.apache.tomcat:tomcat-jdbc:8.5.0"
runtime "org.apache.tomcat.embed:tomcat-embed-logging-log4j:8.5.0"
```

7. In the root of the project folder (eg. demo), run ./gradlew bootRun
8. Wait for it to download and compile the dependencies.
9. Startup failed with an exception stack trace.

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestMappingHandlerMapping' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]: Invocation of init method failed; nested exception is java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
```

#### Prior to the stack trace, there are few messages logged at INFO level:

```
Failed to introspect annotations on [class org.grails.datastore.gorm.boot.autoconfigure.HibernateGormAutoConfiguration$$EnhancerBySpringCGLIB$$6287c085]: java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
```

**Comment by benrhine** [comment]
This is simply due to the fact that Spring Boot 2 (which has just been recently released) is not yet supported. The roadmap for Spring Boot 2 and Java 9  support is forth quarter this year (2018) with the release of Grails 4. Until that time you will need to use Spring Boot 1.5.x in order for Gorm to work correctly.
