### ISSUE TITLE
when will release 9.0.x alpha version？

### ISSUE THREAD

**Issue by xp13910818313** [grails/gorm-hibernate5#873]
Is there a roadmap for 9.0.x version development?  @puneetbehl

**Comment by puneetbehl** [comment]
The 9.0.x version of GORM for Hibernate5 is originally planned to be released around the middle of 3rd quarter this year alongwith Grails 7, update includes:

- Updating Spring, SpringBoot to next major version.
- Baseline to Java 17
- Possibility to upgrade to Hibernate6 but we may need to drop support for a few things or make some major changes, if we try to support Hibernate6 at all with Grails 7 but it is too early say anything.

Having said above, I'm not working on the Grails framework at the moment and not sure what's the plan moving forward.

**Comment by xp13910818313** [comment]
thanks for answer
wish all the best
