### ISSUE TITLE
Something Wrong with gorm-hibernate5-spring-boot : 6.0.0.RELEASE

### ISSUE THREAD

**Issue by SeaEagle** [grails/gorm-hibernate5#9]
Hi,

Eh, I followed the docs and the example ( spring-boot-hibernate5 )  to build a simple spring-boot project with gorm, and I add a dependency in the pom.xml :

```
<dependency>
    <groupId>org.grails</groupId>
    <artifactId>gorm-hibernate5-spring-boot</artifactId>
    <version>6.0.0.RELEASE</version>
</dependency>
```

But, I found it didn't attach some necessary jars to the project. For example, it didn't find the class : grails.persistence.Entity, and I have to add a dependency: grails-datastore-gorm. In the end, I found there are such many jars I have to add to pom.xml by myself.

Finally, I changed 6.0.0.RELEASE to 6.0.0.RC2, and it worked !

 I'm Grails honest fan, and I love gorm very much, it's powerful, so I hope you can provider a better gorm release version.

**Comment by graemerocher** [comment]
6.0.3 seems to work fine
