### ISSUE TITLE
create gorm-hibernate5 8.1.1 release for Grails 6.2.2

### ISSUE THREAD

**Issue by jamesfredley** [grails/gorm-hibernate5#932]
https://docs.google.com/document/d/177i1DJ6iPtuvziXrcMoIOImVqJXfIFxLlOIS5sre72I/edit?tab=t.0#heading=h.iv8c37f5fktv

requires https://github.com/grails/grails-gradle-plugin/issues/353 to remove `-plain` in jar filename.

**Comment by matrei** [comment]
~~Should the title of this ticket not be **create gorm-hibernate5 8.1.3 release for Grails 6.2.2**~~

Scratch that, I was looking at `grails-data-mapping`.

**Comment by jamesfredley** [comment]
https://s01.oss.sonatype.org/#nexus-search;gav~org.grails~grails-datastore-gorm-hibernate5~~~~kw,versionexpand

**Comment by jamesfredley** [comment]
No more `-plain` in jar file name

https://s01.oss.sonatype.org/#nexus-search;gav~org.grails.plugins~hibernate5~~~~kw,versionexpand

![image](https://github.com/user-attachments/assets/4e44a7cd-b9e8-4325-a5f7-6f8a2bc5e657)
