### ISSUE TITLE
Update to embedded component not persisted

### ISSUE THREAD

**Issue by namgang** [grails/gorm-hibernate5#97]
This is about updating a property of an embedded component. It seems the dirty flag of the enclosing domain instance is not necessarily set. The outcome is that the instance is not persisted.

Grails 3.3.6
Hibernate plugin 6.1.10.BUILD-SNAPSHOT
Oracle JDK 1.8.0_171
Ubuntu 16.04.4 LTS

Sample app: https://bitbucket.org/sodastream/grails336-embedded-issue/

The app has 3 steps (see the README):
1. Create and save a domain instance including an embedded property. -- OK
2. Find the instance, update an embedded property and save. -- The change is not persisted
3. Find the instance, update both a non-embedded property of the domain instance and the embedded property and save. -- The change is persisted.

There is debug logging that shows that the instance is really updated in memory.

Conclusion: It seems that if an update only involves embedded data a domain instance is not persisted.

**Comment by ilopmar** [comment]
You need to annotate the embedded class with `@DirtyCheck`. Please take a look at this: http://gorm.grails.org/6.1.x/hibernate/manual/#_dirty_checking_for_embedded_classes

**Comment by namgang** [comment]
Gosh, I did a RTFM (blushing)!

/Hakan
 

    On Wednesday, July 11, 2018, 9:06:39 AM GMT+2, Iván López <notifications@github.com> wrote:  
 
 
Closed #97.
